title: Dr Daniel Burnham
logo: "/images/logo.jpg?raw=true"
description: >
  Interdisciplinary Physicist & Engineer with 20 years experience developing advanced optical, holographic and biophysical instrumentation.
  <br><br>
  Specialist in holography, waveguides, diffractive optics, microscopy, single-molecule biophysics, and optical traps.
  <br><br>
  14 patents &bull; 30 peer-reviewed publications &bull; ~2,000 citations
  <br><br>
  <a href="https://www.linkedin.com/in/daniel-r-burnham/">LinkedIn</a>

github:
  project_title: "View Repositories"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
